---
- name: Create auto-upgrade folder for client
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ burp_server_autoupgrade_dir }}/win64/{{ burp_autoupgrade_version }}"

- name: Copy auto-upgrade scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "autoupgrade_script", dest: "{{ burp_server_autoupgrade_dir }}/win64/script"}

- name: Download packages
  ansible.builtin.get_url:
    url: "{{ item.src }}"
    dest: "{{ item.dest }}"
    timeout: 30
    validate_certs: false
  with_items:
    - "{{ burp_autoupgrade_package_copy }}"
