---
- name: "Delete default clientconfdir"
  ansible.builtin.file:
    path: "/etc/burp/clientconfdir"
    state: absent
  notify:
    - Restart burp-server

- name: "Copy burp-server.conf"
  ansible.builtin.template:
    src: "burp-server.conf.j2"
    dest: "{{ burp_server_etc }}/burp-server.conf"
  notify: Restart burp-server

- name: "Copy include files"
  ansible.builtin.template:
    src: incexc/IncludeTemplate.j2
    dest: "{{ burp_clientconf_path_dir_incexc }}/{{ item.name }}"
  with_items: "{{ burp_incexc_templates }}"
  notify: Restart burp-server

- name: "Create client's configurations"
  ansible.builtin.template:
    src: profiles/new_client.j2
    dest: "{{ burp_clientconf_path_dir }}/{{ item.name }}"
  with_items: "{{ burp_add_clients | default([]) }}"
