---
- name: "Create CA folder for supervisor"
  ansible.builtin.file:
    path: "{{ burp_client_ca_csr_dir }}"
    state: directory

- name: "Configure local client"
  ansible.builtin.template:
    src: burp.conf.j2
    dest: "{{ burp_server_etc }}/burp.conf"

- name: "Add local client in clientconfdir"
  ansible.builtin.template:
    src: monitor.j2
    dest: "{{ burp_clientconf_path_dir }}/monitor"
