---
- name: "Remove clients file in clientconfdir"
  file:
    path: "{{ burp_server_clientconfdir }}/{{ item.name }}"
    state: absent
  with_items: "{{ burp_remove_clients }}"

- name: "Delete clients data folder"
  file:
    path: "{{ burp_data_backup }}/{{ item.name }}"
    state: absent
  with_items: "{{ burp_remove_clients }}"

- name: "Delete clients certificate"
  file:
    path: "{{ burp_server_etc }}/CA/{{ item.name }}.crt"
    state: absent
  with_items: "{{ burp_remove_clients }}"

- name: "Delete client CSR"
  file:
    path: "{{ burp_server_etc }}/CA/{{ item.name }}.csr"
    state: absent
  with_items: "{{ burp_remove_clients }}"
