---
- name: "Add burp Service"
  template:
    src: "burp-server.j2"
    dest: "/etc/systemd/system/burp-server.service"
  notify: Reload systemctl daemon

- name: "Activate Burp service"
  service:
    name: burp-server
    state: started
    enabled: true
