---
- name: "Add burp Service"
  ansible.builtin.template:
    src: "burp-server.j2"
    dest: "/etc/systemd/system/burp-server.service"
  notify:
    - Reload systemctl daemon
    - Activate Burp service

- name: Flush handlers
  meta: flush_handlers
