---
- name: Reload systemctl daemon
  systemd:
    daemon_reload: true

- name: "Activate Burp service"
  service:
    name: burp-server
    state: started
    enabled: true

- name: Restart burp-server
  service:
    name: burp-server
    state: restarted
