---
- name: Reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Activate Burp service"
  ansible.builtin.service:
    name: burp-server
    state: started
    enabled: true

- name: Restart burp-server
  ansible.builtin.service:
    name: burp-server
    state: restarted
